name: Maxium Code Eval

on:
  pull_request:
    types:
      - opened
      - synchronizd

jobs:
  code-eval:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install requests
      - name: Maxium Code Eval Action
        uses: maxium-ai/code-eval-action@master
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          maxium-ai-api-key: "secret_live_moNmhZOrjQ_LLy-YZw58_vz_IqcxyizsFO3qIFS515M"
